Repository hmcts/jps-judicial-payment-frontend, pull requests merged in 2023-07, with the labels that each got.

#34 IJPS-60: Update node ver in nvmrc
  .nvmrc
Labels: ns:jps, prd:jps, rel:jps-judicial-payment-frontend-pr-34

#40 pipeline resolution
  src/app/components/routing/application-routing.component.spec.ts
  yarn-audit-known-issues
Labels: ns:jps, prd:jps, keep-helm, rel:jps-judicial-payment-frontend-pr-40

#41 change mc to jps in values.yaml
  charts/jps-judicial-payment-frontend/Chart.yaml
  charts/jps-judicial-payment-frontend/values.yaml
Labels: ns:jps, prd:jps, keep-helm, rel:jps-judicial-payment-frontend-pr-41

#42 implement http loader, implement logger
  api/refdata/locations/index.ts
  config/default.json
  package.json
  server.ts
  src/app/app.component.html
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/cookies/cookie-manager/cookie-manager.component.ts
  src/app/loader/loader.component.html
  src/app/loader/loader.component.scss
  src/app/loader/loader.component.spec.ts
  src/app/loader/loader.component.ts
  yarn.lock
Labels: ns:jps, prd:jps, keep-helm, rel:jps-judicial-payment-frontend-pr-42

#32 IJPS-71
  Jenkinsfile_CNP
  README.md
  test/end-to-end/codecept.conf.js
  test/end-to-end/pages/steps_file.js
  test/end-to-end/paths/F-001_LoginFeature_test.js
  test/end-to-end/paths/hello_world test_test.js
  yarn-audit-known-issues
Labels: ns:jps, prd:jps, keep-helm, rel:jps-judicial-payment-frontend-pr-32

#49 IJPS-33 and 36 FTS
  test/end-to-end/pages/ManageJudicialSittingRecordsPage.js
  test/end-to-end/pages/steps_file.js
  test/end-to-end/paths/F-001_LoginFeature_test.js
  test/end-to-end/paths/F-006_JudicialSittingRecordsPageFeature_test.js
  test/end-to-end/steps.d.ts
Labels: ns:jps, prd:jps, rel:jps-judicial-payment-frontend-pr-49

#25 IJPS-35
  angular.json
  api/configuration/references.ts
  api/refdata/locations/index.ts
  api/sittingRecords/index.ts
  api/sittingRecords/routes.ts
  config/custom-environment-variables.json
  config/default.json
  package.json
  proxy.config.json
  server.ts
  src/app/_models/viewSittingRecords.model.ts
  src/app/_pipes/convertTableStatus.ts
  src/app/_services/date-service/date-service.spec.ts
  src/app/_services/date-service/date-service.ts
  src/app/_services/default-dt-options.ts
  src/app/_services/sitting-records-service/view-sitting-records-service.spec.ts
  src/app/_services/sitting-records-service/view-sitting-records-service.ts
  src/app/_workflows/sitting-record-workflow.service.spec.ts
  src/app/_workflows/sitting-record-workflow.service.ts
  src/app/app.component.html
  src/app/app.module.ts
  src/app/sitting-records/sitting-records.module.ts
  src/app/sitting-records/view-sitting-records/view-sitting-records.component.html
  src/app/sitting-records/view-sitting-records/view-sitting-records.component.scss
  src/app/sitting-records/view-sitting-records/view-sitting-records.component.spec.ts
  src/app/sitting-records/view-sitting-records/view-sitting-records.component.ts
  src/assets/sort.svg
  src/assets/sort_down.svg
  src/assets/sort_up.svg
  src/styles.scss
  src/styles/datatable_overrides.scss
  yarn-audit-known-issues
  yarn.lock
Labels: ns:jps, prd:jps, keep-helm, rel:jps-judicial-payment-frontend-pr-25

#58 Fixing broken functional test @S-006.6
  test/end-to-end/pages/steps_file.js
  test/end-to-end/paths/F-006_JudicialSittingRecordsPageFeature_test.js
Labels: ns:jps, prd:jps, keep-helm, rel:jps-judicial-payment-frontend-pr-58

#53 Functional tests for IJPS-70
  Jenkinsfile_CNP
  test/end-to-end/codecept.conf.js
  test/end-to-end/pages/ManageJudicialSittingRecordsPage.js
  test/end-to-end/pages/steps_file.js
  test/end-to-end/paths/F-006_ManageJudicialSittingRecordsPageFeature_test.js
Labels: ns:jps, prd:jps, rel:jps-judicial-payment-frontend-pr-53
