Repository hmcts/jps-judicial-payment-frontend, pull requests merged in 2023-10, with the labels that each got.

#47 IJPS-72
  src/app/_guards/sitting-records/sitting-records-landing.guard.ts
  src/app/_guards/sitting-records/sitting-records-submit.guard.spec.ts
  src/app/_guards/sitting-records/sitting-records-submit.guard.ts
  src/app/_guards/sitting-records/sitting-records-view.guard.spec.ts
  src/app/_guards/sitting-records/sitting-records-view.guard.ts
  src/app/_models/viewSittingRecords.model.ts
  src/app/_services/default-dt-options.ts
  src/app/_workflows/duplicate-record-workflow.service.spec.ts
  src/app/_workflows/duplicate-record-workflow.service.ts
  src/app/_workflows/recorder-workflow.service.spec.ts
  src/app/_workflows/recorder-workflow.service.ts
  src/app/_workflows/submitter-workflow.service.spec.ts
  src/app/_workflows/submitter-workflow.service.ts
  src/app/components/routing/application-routing.component.ts
  src/app/sitting-records/add-sitting-record/add-sitting-record-success/add-sitting-record-success.component.spec.ts
  src/app/sitting-records/add-sitting-record/add-sitting-record-success/add-sitting-record-success.component.ts
  src/app/sitting-records/add-sitting-record/add-sitting-record.component.spec.ts
  src/app/sitting-records/add-sitting-record/add-sitting-record.component.ts
  src/app/sitting-records/add-sitting-record/add-sitting-records-confirm/add-sitting-records-confirm.component.spec.ts
  src/app/sitting-records/add-sitting-record/add-sitting-records-confirm/add-sitting-records-confirm.component.ts
  src/app/sitting-records/delete-sitting-records/delete-sitting-records.component.spec.ts
  src/app/sitting-records/delete-sitting-records/delete-sitting-records.component.ts
  src/app/sitting-records/duplicate-sitting-records/duplicate-confirm/duplicate-confirm-success/duplicate-confirm-success.component.spec.ts
  src/app/sitting-records/duplicate-sitting-records/duplicate-confirm/duplicate-confirm-success/duplicate-confirm-success.component.ts
  src/app/sitting-records/duplicate-sitting-records/duplicate-confirm/duplicate-existing-confirm/duplicate-existing-confirm.component.spec.ts
  src/app/sitting-records/duplicate-sitting-records/duplicate-confirm/duplicate-existing-confirm/duplicate-existing-confirm.component.ts
  src/app/sitting-records/duplicate-sitting-records/invalid-duplicate/invalid-duplicate.component.scss
  src/app/sitting-records/duplicate-sitting-records/invalid-duplicate/invalid-duplicate.component.spec.ts
  src/app/sitting-records/duplicate-sitting-records/invalid-duplicate/invalid-duplicate.component.ts
  src/app/sitting-records/duplicate-sitting-records/potential-duplicate/potential-duplicate.component.scss
  src/app/sitting-records/duplicate-sitting-records/potential-duplicate/potential-duplicate.component.spec.ts
  src/app/sitting-records/duplicate-sitting-records/potential-duplicate/potential-duplicate.component.ts
  src/app/sitting-records/duplicate-sitting-records/valid-sitting-records/valid-sitting-records.component.spec.ts
  src/app/sitting-records/duplicate-sitting-records/valid-sitting-records/valid-sitting-records.component.ts
  src/app/sitting-records/manage-sitting-records/manage-sitting-records.component.html
  src/app/sitting-records/manage-sitting-records/manage-sitting-records.component.spec.ts
  src/app/sitting-records/manage-sitting-records/manage-sitting-records.component.ts
  src/app/sitting-records/sitting-records-info-banner/sitting-records-info-banner.component.spec.ts
  src/app/sitting-records/sitting-records-info-banner/sitting-records-info-banner.component.ts
  src/app/sitting-records/sitting-records-landing/sitting-records-landing-manage-records/sitting-records-landing-manage-records.component.html
  src/app/sitting-records/sitting-records-landing/sitting-records-landing-manage-records/sitting-records-landing-manage-records.component.ts
  src/app/sitting-records/sitting-records-landing/sitting-records-landing.component.spec.ts
  src/app/sitting-records/sitting-records-landing/sitting-records-landing.component.ts
  src/app/sitting-records/sitting-records-routing.module.ts
  src/app/sitting-records/sitting-records.module.ts
  src/app/sitting-records/submit-sitting-records/submit-sitting-records.component.html
  src/app/sitting-records/submit-sitting-records/submit-sitting-records.component.scss
  src/app/sitting-records/submit-sitting-records/submit-sitting-records.component.spec.ts
  src/app/sitting-records/submit-sitting-records/submit-sitting-records.component.ts
  src/app/sitting-records/view-sitting-records/view-sitting-records.component.spec.ts
  src/app/sitting-records/view-sitting-records/view-sitting-records.component.ts
  src/app/static-elements/logout/logout.component.html
  src/styles.scss
  yarn-audit-known-issues
  yarn.lock
Labels: ns:jps, prd:jps, keep-helm, rel:jps-judicial-payment-frontend-pr-47, enable_keep_helm

#76 add yarn install to test command
  package.json
Labels: ns:jps, prd:jps, keep-helm, enable_keep_helm, rel:jps-judicial-payment-frontend-pr-76

#77 Test Fixes
  src/app/app.component.html
  test/end-to-end/pages/ManageJudicialSittingRecordsPage.js
  test/end-to-end/paths/F-006_ManageJudicialSittingRecordsPageFeature_test.js
Labels: ns:jps, prd:jps, keep-helm, enable_keep_helm, rel:jps-judicial-payment-frontend-pr-77

#80 IJPS-116: Jenkins enabled staging deployment and sync with other bran…
  Jenkinsfile_CNP
Labels: ns:jps, prd:jps, rel:jps-judicial-payment-frontend-pr-80

#79 Test fix
  src/index.html
  test/end-to-end/paths/F-006_ManageJudicialSittingRecordsPageFeature_test.js
Labels: ns:jps, prd:jps, keep-helm, enable_keep_helm, rel:jps-judicial-payment-frontend-pr-79

#81 PR to fix master - yarn audit file
  yarn-audit-known-issues
Labels: ns:jps, prd:jps, rel:jps-judicial-payment-frontend-pr-81

#83 Bump chart node.js ver
  charts/jps-judicial-payment-frontend/Chart.yaml
  yarn-audit-known-issues
Labels: ns:jps, prd:jps, rel:jps-judicial-payment-frontend-pr-83

#60 FTs for IJPS-43
  test/end-to-end/pages/AddSittingRecordsPage.js
  test/end-to-end/pages/ConfirmNewSittingRecordsPage.js
  test/end-to-end/pages/JudicialSittingRecordsPage.js
  test/end-to-end/pages/steps_file.js
  test/end-to-end/paths/F-002_CreateNewSittingRecordsFeature_test.js
Labels: ns:jps, prd:jps, rel:jps-judicial-payment-frontend-pr-60, enable_keep_helm

#87 FT: Add retries to login functions
  test/end-to-end/pages/steps_file.js
  yarn-audit-known-issues
Labels: ns:jps, prd:jps, enable_keep_helm, rel:jps-judicial-payment-frontend-pr-87

#88 increasing retries for FT login functions
  test/end-to-end/pages/steps_file.js
Labels: ns:jps, prd:jps, rel:jps-judicial-payment-frontend-pr-88

#89 FT- adding retries to config and login functions
  test/end-to-end/codecept.conf.js
  test/end-to-end/pages/steps_file.js
  yarn-audit-known-issues
Labels: ns:jps, prd:jps, enable_keep_helm, rel:jps-judicial-payment-frontend-pr-89

#55 IJPS-90 FTs for IJPS-35 (search sitting records)
  test/end-to-end/pages/JudicialSittingRecordsPage.js
  test/end-to-end/paths/F-003_SearchSittingRecordsFeature_test.js
Labels: ns:jps, prd:jps, keep-helm, enable_keep_helm, rel:jps-judicial-payment-frontend-pr-55

#91 IJPS-127
  src/app/sitting-records/add-sitting-record/add-sitting-record-success/add-sitting-record-success.component.spec.ts
  src/app/sitting-records/add-sitting-record/add-sitting-record-success/add-sitting-record-success.component.ts
  src/app/sitting-records/delete-sitting-records/delete-sitting-records.component.ts
  src/app/sitting-records/duplicate-sitting-records/invalid-duplicate/invalid-duplicate.component.html
  src/app/sitting-records/duplicate-sitting-records/invalid-duplicate/invalid-duplicate.component.ts
  src/app/sitting-records/duplicate-sitting-records/potential-duplicate/potential-duplicate.component.html
  src/app/sitting-records/duplicate-sitting-records/potential-duplicate/potential-duplicate.component.ts
  src/app/sitting-records/duplicate-sitting-records/valid-sitting-records/valid-sitting-records.component.ts
  src/app/sitting-records/manage-sitting-records/manage-sitting-records.component.html
  src/app/sitting-records/manage-sitting-records/manage-sitting-records.component.spec.ts
  src/app/sitting-records/manage-sitting-records/manage-sitting-records.component.ts
  src/app/sitting-records/sitting-records-info-banner/sitting-records-info-banner.component.spec.ts
  src/app/sitting-records/sitting-records-info-banner/sitting-records-info-banner.component.ts
  src/app/sitting-records/view-sitting-records/view-sitting-records.component.spec.ts
  src/app/sitting-records/view-sitting-records/view-sitting-records.component.ts
  test/end-to-end/paths/F-003_SearchSittingRecordsFeature_test.js
  yarn-audit-known-issues
Labels: ns:jps, prd:jps, keep-helm, enable_keep_helm, rel:jps-judicial-payment-frontend-pr-91

#95 Fixing FTs
  test/end-to-end/codecept.conf.js
  test/end-to-end/pages/steps_file.js
  test/end-to-end/paths/F-001_LoginFeature_test.js
  test/end-to-end/paths/F-002_CreateNewSittingRecordsFeature_test.js
  test/end-to-end/paths/F-003_SearchSittingRecordsFeature_test.js
  test/end-to-end/paths/F-006_ManageJudicialSittingRecordsPageFeature_test.js
Labels: ns:jps, prd:jps, enable_keep_helm, rel:jps-judicial-payment-frontend-pr-95

#97 update config for redis
  api/auth/index.ts
  api/configuration/references.ts
  config/custom-environment-variables.json
  config/default.json
Labels: ns:jps, prd:jps, rel:jps-judicial-payment-frontend-pr-97

#68 IJPS-96
  src/app/_guards/sitting-records/sitting-records-manage.guard.spec.ts
  src/app/_models/addSittingRecords.model.ts
  src/app/_models/sittingRecord.model.ts
  src/app/_pipes/convertRoleIdToString.ts
  src/app/_services/delete-sitting-records-http-service.spec.ts
  src/app/_services/delete-sitting-records-http-service.ts
  src/app/_services/user-service/user.service.ts
  src/app/_workflows/duplicate-record-workflow.service.spec.ts
  src/app/_workflows/duplicate-record-workflow.service.ts
  src/app/_workflows/recorder-workflow.service.spec.ts
  src/app/_workflows/recorder-workflow.service.ts
  src/app/app.component.ts
  src/app/sitting-records/add-sitting-record/add-sitting-record.component.html
  src/app/sitting-records/add-sitting-record/add-sitting-record.component.ts
  src/app/sitting-records/delete-sitting-records/delete-sitting-records.component.html
  src/app/sitting-records/delete-sitting-records/delete-sitting-records.component.spec.ts
  src/app/sitting-records/delete-sitting-records/delete-sitting-records.component.ts
  src/app/sitting-records/duplicate-sitting-records/duplicate-confirm/duplicate-option-confirm/duplicate-confirm.component.spec.ts
  src/app/sitting-records/duplicate-sitting-records/duplicate-sitting-records.component.ts
  src/app/sitting-records/duplicate-sitting-records/invalid-duplicate/invalid-duplicate.component.spec.ts
  src/app/sitting-records/duplicate-sitting-records/invalid-duplicate/invalid-duplicate.component.ts
  src/app/sitting-records/duplicate-sitting-records/potential-duplicate/potential-duplicate.component.spec.ts
  src/app/sitting-records/duplicate-sitting-records/potential-duplicate/potential-duplicate.component.ts
  src/app/sitting-records/duplicate-sitting-records/valid-sitting-records/valid-sitting-records.component.spec.ts
  src/app/sitting-records/duplicate-sitting-records/valid-sitting-records/valid-sitting-records.component.ts
  src/app/sitting-records/shared-components/user-search/user-search.component.html
  src/app/sitting-records/shared-components/user-search/user-search.component.scss
  src/app/sitting-records/shared-components/user-search/user-search.component.spec.ts
  src/app/sitting-records/shared-components/user-search/user-search.component.ts
  src/app/sitting-records/shared-components/venue/venue.component.ts
  src/app/sitting-records/sitting-records-info-banner/sitting-records-info-banner.component.spec.ts
  src/app/sitting-records/sitting-records-landing/sitting-records-landing-johadmin/sitting-records-landing-johadmin.component.html
  src/app/sitting-records/sitting-records-landing/sitting-records-landing-johadmin/sitting-records-landing-johadmin.component.scss
  src/app/sitting-records/sitting-records-landing/sitting-records-landing-johadmin/sitting-records-landing-johadmin.component.spec.ts
  src/app/sitting-records/sitting-records-landing/sitting-records-landing-johadmin/sitting-records-landing-johadmin.component.ts
  src/app/sitting-records/sitting-records-landing/sitting-records-landing.component.html
  src/app/sitting-records/sitting-records-landing/sitting-records-landing.component.spec.ts
  src/app/sitting-records/sitting-records-landing/sitting-records-landing.component.ts
  src/app/sitting-records/sitting-records.module.ts
  src/app/sitting-records/submit-sitting-records/submit-sitting-records.component.ts
  test/end-to-end/pages/AddSittingRecordsPage.js
  test/end-to-end/pages/JudicialSittingRecordsPage.js
  test/end-to-end/paths/F-006_ManageJudicialSittingRecordsPageFeature_test.js
Labels: ns:jps, prd:jps, keep-helm, enable_keep_helm, rel:jps-judicial-payment-frontend-pr-68

#98 Ijps redis
  charts/jps-judicial-payment-frontend/Chart.yaml
  charts/jps-judicial-payment-frontend/values.aat.template.yaml
  charts/jps-judicial-payment-frontend/values.yaml
Labels: ns:jps, prd:jps, rel:jps-judicial-payment-frontend-pr-98

#101 update values.yaml
  charts/jps-judicial-payment-frontend/Chart.yaml
  charts/jps-judicial-payment-frontend/values.yaml
Labels: ns:jps, prd:jps, rel:jps-judicial-payment-frontend-pr-101

#102 update logging
  api/auth/index.ts
Labels: ns:jps, prd:jps, rel:jps-judicial-payment-frontend-pr-102
